### ISSUE TITLE
Play archetype example does not work, exception thrown

### ISSUE THREAD

**Issue by sreplans** [vibe-project/vibe-examples#1]
Hi,
I am getting Execution exception[[UnsupportedOperationException: Play Java API doesn't allow to receive text and binary frame together in a single connection]] when running the sample server with the sample client. 
Full stack trace:
play.api.Application$$anon$1: Execution exception[[UnsupportedOperationException: Play Java API doesn't allow to receive text and binary frame together in a single connection]]
    at play.api.Application$class.handleError(Application.scala:296) ~[play_2.11-2.3.2.jar:2.3.2]
    at play.api.DefaultApplication.handleError(Application.scala:402) [play_2.11-2.3.2.jar:2.3.2]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$messageReceived$2.applyOrElse(PlayDefaultUpstreamHandler.scala:229) [play_2.11-2.3.2.jar:2.3.2]
    at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$messageReceived$2.applyOrElse(PlayDefaultUpstreamHandler.scala:227) [play_2.11-2.3.2.jar:2.3.2]
    at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [scala-library-2.11.1.jar:na]
Caused by: java.lang.UnsupportedOperationException: Play Java API doesn't allow to receive text and binary frame together in a single connection
    at org.atmosphere.vibe.platform.bridge.play2.PlayServerWebSocket.binaryAction(PlayServerWebSocket.java:61) ~[vibe-platform-bridge-play2-3.0.0-Alpha9.jar:na]
    at org.atmosphere.vibe.transport.ws.WebSocketTransportServer$DefaultTransport.<init>(WebSocketTransportServer.java:80) ~[vibe-server-3.0.0-Alpha15.jar:na]
    at org.atmosphere.vibe.transport.ws.WebSocketTransportServer.on(WebSocketTransportServer.java:60) ~[vibe-server-3.0.0-Alpha15.jar:na]
    at org.atmosphere.vibe.example.platform.play2.Bootstrap$2.onReady(Bootstrap.java:58) ~[na:na]
    at play.core.j.JavaWebSocket$$anonfun$webSocketWrapper$1$$anonfun$apply$1$$anonfun$apply$3$$anonfun$apply$4.apply(JavaWebSocket.scala:71) ~[play_2.11-2.3.2.jar:2.3.2]
on socket: /vibe?transport=longpoll&_=6&when=open
java.nio.channels.ClosedChannelException
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.cleanUpWriteBuffer(AbstractNioWorker.java:433)
    at org.jboss.netty.channel.socket.nio.AbstractNioWorker.writeFromUserCode(AbstractNioWorker.java:128)
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServerSocketPipelineSink.java:99)
    at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:36)
    at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:60)
    at com.typesafe.netty.http.pipelining.HttpPipeliningHandler.handleDownstream(HttpPipeliningHandler.java:88)
    at play.core.server.netty.NettyResultStreamer$.sendDownstream(NettyResultStreamer.scala:196)
    at play.core.server.netty.NettyResultStreamer$$anonfun$bufferingIteratee$1.apply(NettyResultStreamer.scala:121)
    at play.core.server.netty.NettyResultStreamer$$anonfun$bufferingIteratee$1.apply(NettyResultStreamer.scala:115)
    at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$13.apply(Iteratee.scala:495)
    at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$13.apply(Iteratee.scala:495)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
    at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:46)
    at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
    at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
    at scala.concurrent.Promise$class.complete(Promise.scala:55)
    at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:23)
    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by flowersinthesand** [comment]
I found there are two problems: one for WebSocket resource and one for HTTP resource. 1st problem will be fixed in Vibe Java Platform 3.0.0-Beta1 and 2nd problem can be fixed by replacing `BodyParser.TolerantText` with `BodyParser.Raw`. I'll update the source soon.

Thanks for the report.

**Comment by flowersinthesand** [comment]
For 1st problem, https://github.com/vibe-project/vibe-java-platform/issues/45
